### ISSUE TITLE
[Feature Request] Daylight/Darkness Detection and/or Toggle

### ISSUE THREAD

**Issue by ZhornLegacy** [Frstrm/TokenLightCondition#15]
Doing a test run of this module, and I like it's general behaviour in dark dungeons with torches, etc.
Actually love the design direction; this is a really cool project.
Issue I have though is on scenes set for daylight / global illumination the module is still firing away based on the presence of placed light sources despite the entire scene being illuminated, making tokens as dim/dark even when in fully lit areas.

![image](https://user-images.githubusercontent.com/106674701/211037425-ac78c9ab-4d56-4e52-bffb-f6abf2044ec3.png)
Some means of either automatically toggling the module off when Transitioned to Daylight /  Darkness Level is set to 0 and back on when Transitioning to Darkness / Darkness Level is set to 1 (or >0), and/or a conveniently placed button on the lighting controls to disable/enable the module's automation.

Current setup requires disabling the module as a whole and reloading when transitioning to scenes that are globally illuminated to prevent dim/dark effects from being applied to tokens that shouldn't be, with a lot of manually toggling off each dim/dark effect that way applied just because a token was not close enough to a placed light source despite being fully lit.

**Comment by Frstrm** [comment]
Currently you can disable the tokens effects, and or hud from the module settings.  However the effects option is GM side options.
But I can see how a 'faster' option or toggle might be handy.  I'll take a look at that.

Canvas darkness.  When doing initial calculations, i'm assuming the token is starting in the dark, and checking for light sources to bump the light level.  I don't have a good method yet to say the canvas is Day, but your in cave/room/enclosure so downgrade the light level...( I've seen many maps with both an outdoor and underground setting ) that leads to conflicts of which is the right path ( upgrade/downgrade light level ).  The only exception, is the use of the drawings light overrides (PV), since that seems like an implicit call on the authors part, that that part of the map should be a specific light level.
