### ISSUE TITLE
Issues with Large Creatures

### ISSUE THREAD

**Issue by McShaker** [Frstrm/TokenLightCondition#29]
It appears the light needs to cover the entire token to have the effect applied.

This results in the light source needing to be closer in order to be applied/removed for tokens larger than 1x1.

While using a torch with 15 feet bright the effect is not being removed until within 5 feet of a large creature or 0 feet (touching) a Huge Creature.

**Comment by Frstrm** [comment]
I'm currently using center of token for calculation.  I plan to add more points ( corners/sides ) in the future, but that could impact perf.  One thing I don't want this module to do, is to officiate based how much % square had to be covered to be considered one condition or another.  That's why it only adds an effect, and doesn't influence any stats, or rolls ( unless you tack those on yourself ).  I figure if the light hits that center point, then it's probably a good call to say the token is in that light condition.
Is the token in question, being scaled by a spell or some other method ( enlarge/reduction spells for instance )?

**Comment by Frstrm** [comment]
Unable to repro, and no further information to replicate to work with.  Closing.
