### ISSUE TITLE
Turn off chat notifications. 

### ISSUE THREAD

**Issue by Orionox** [Frstrm/TokenLightCondition#60]
I don't know if I'm missing an option, but it would be nice if I could turn off the chat notifications. They just fill the chat up so fast.

**Comment by Frstrm** [comment]
There are no options available because this module doesn't post any notifications... I think you'll find those notifications are coming either from foundry core or from some other module that indicates when effects are added/removed from tokens ( example: dfreds convenient effects has options for turning on/off chat notifications )
Which of the effects type do you have selected in the module?  ( CE? )
