### ISSUE TITLE
Effects not generated in PF2E

### ISSUE THREAD

**Issue by liquidsonic** [Frstrm/TokenLightCondition#68]
Getting errors with grabbing flags it seems :(

**Comment by liquidsonic** [comment]
![image](https://github.com/Frstrm/TokenLightCondition/assets/18706361/e1aa27f7-bdaf-43cb-a5ad-15dc43290edd)

![image](https://github.com/Frstrm/TokenLightCondition/assets/18706361/699d343b-8c65-47c4-bd1f-570a49bb1a30)

**Comment by liquidsonic** [comment]
on an added note, I commented out the flags just to see what happens

It seems it still doesn't know how to create the effect on the token. Just returns

actor cannot be undefined. So seems the method for grabbing that token from the HUD isn't grabbing

**Comment by liquidsonic** [comment]
On even further investigation, by creating the effects matching the specs in the code it seems to work as intended now.(Thank you for including some logging settings !)

Seems to be that it isnt creating the effects in the world which is getting skipped somehow so it its reference nothing

**Comment by Frstrm** [comment]
I'm not up to speed on all of the recent changes around affects myself at the moment, ( especially this core.statusId change.  I'm interested in where you found the specs, or at your local changes to see an example of your change that works. )
I'm primarily in Maintenance mode with this module, since I'm not actively making more changes to it, since it met my needs at the time.

**Comment by Frstrm** [comment]
I have a fix for both the item effects being created if they don't exist ( pf2e ), and for the undefined flags error.  Should be in the next update...
